services:
  nginx:
    image: nginx:alpine
    container_name: private-tf-runners-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RUNNERS_FRONTEND_URL=${RUNNERS_FRONTEND_URL:-https://runners.lan}
      - RUNNERS_API_URL=${RUNNERS_API_URL:-https://api.runners.lan}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    command: sh -c "envsubst '$$RUNNERS_FRONTEND_URL $$RUNNERS_API_URL' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    #restart: unless-stopped
    networks:
      - tf-registry-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: private-tf-runners-backend
    expose:
      - "8080"
    volumes:
      - backend-data:/data
    env_file:
      - .env
    environment:
      - RUNNERS_DATABASE_PATH=/data/runners.db
    restart: unless-stopped
    networks:
      - tf-registry-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: private-tf-runners-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=${RUNNERS_API_URL}
    networks:
      - tf-registry-network
volumes:
  backend-data:
    driver: local
networks:
  tf-registry-network:
    name: tf-registry-network